version: '3.8'
services:
  postgres:
    image: postgres:11.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: docker-fullstack-db
    ports:
      - 5432:5432
    volumes:
      - ./dbscripts:/docker-entrypoint-initdb.d
  server:
    build: ./server
    volumes:
      - ./server:/server
    ports: 
      - 8080:8080
    depends_on:
      - postgres
  web:
    build:
      context: ./web
    environment:
      ENV: development       # Choose one: development/production
    volumes:
      - ./web:/web
    ports:
      - 3000:3000
    depends_on:
      - server